from .agent import CLI_AGENT_PROMPT
from .contracts import (
    BASIC_INFO_PROMPT,
    CONTRACT_INTEGRITY_PROMPT,
    CROSS_PAGE_SEAL_PROMPT,
    SEAL_REVIEW_PROMPT,
    VALIDITY_REVIEW_PROMPT,
)
from .documents import OCR_STRUCTURE_PROMPT

__all__ = [
    "BASIC_INFO_PROMPT",
    "CLI_AGENT_PROMPT",
    "CONTRACT_INTEGRITY_PROMPT",
    "CROSS_PAGE_SEAL_PROMPT",
    "OCR_STRUCTURE_PROMPT",
    "SEAL_REVIEW_PROMPT",
    "VALIDITY_REVIEW_PROMPT",
]
